/*
 *  Librarian for KiCad, a free EDA CAD application.
 *  The dialog with the templates for new footprints.
 *
 *  Copyright (C) 2013-2015 CompuPhase
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may not
 *  use this file except in compliance with the License. You may obtain a copy
 *  of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 *
 *  $Id: libmngr_dlgnewfootprint.h 5435 2016-02-15 12:20:33Z thiadmer $
 */
#ifndef __libmngr_dlgnewfootprint__
#define __libmngr_dlgnewfootprint__

/**
@file
Subclass of DlgNewFootprint, which is generated by wxFormBuilder.
*/

#include "libmngr_gui_base.h"

//// end generated include

/** Implementing DlgNewFootprint */
class libmngrDlgNewFootprint : public DlgNewFootprint
{
	public:
		/** Constructor */
		explicit libmngrDlgNewFootprint(wxWindow* parent);
	//// end generated class members

		void OnTemplateSelect(wxCommandEvent& event);
		void OnNextImage(wxSpinEvent& event);
		void OnPrevImage(wxSpinEvent& event);
		void OnOk(wxCommandEvent& event);

		wxString GetTemplateName() const { return m_templatename; }
		wxString GetFootprintName() const { return m_partname; }

		/** SetLibraryName() to test whether a footprint exists in the library,
		 *  set the full path to the library before calling ShowModal() */
		void SetLibraryName(const wxString& filename) { m_libraryname = filename; }

	private:
		wxString m_templatename;	/* just the "base" name, without path or extension*/
		wxString m_partname;		/* name for the footprint (output of the dialog) */
		wxString m_libraryname;	    /* name of the library where the new footprint must be stored in */
        wxArrayString m_previews;   /* paths to bitmaps with preview images */
        int m_currentpreview;
};

#endif // __libmngr_dlgnewfootprint__
