/*
 *  Librarian for KiCad, a free EDA CAD application.
 *  The dialog with the templates for new symbols.
 *
 *  Copyright (C) 2013-2014=5 CompuPhase
 *
 *  Licensed under the Apache License, Version 2.0 (the "License"); you may not
 *  use this file except in compliance with the License. You may obtain a copy
 *  of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 *  License for the specific language governing permissions and limitations
 *  under the License.
 *
 *  $Id: libmngr_dlgnewsymbol.h 5686 2017-05-24 13:56:46Z thiadmer $
 */
#ifndef __libmngr_dlgnewsymbol__
#define __libmngr_dlgnewsymbol__

/**
@file
Subclass of DlgNewSymbol, which is generated by wxFormBuilder.
*/

#include "libmngr_gui_base.h"

//// end generated include

/** Implementing DlgNewSymbol */
class libmngrDlgNewSymbol : public DlgNewSymbol
{
  public:
    /** Constructor */
    explicit libmngrDlgNewSymbol(wxWindow* parent);

  protected:
    // Handlers for DlgNewSymbol events.
    void OnTemplateSelect(wxCommandEvent& event);
    void OnOk(wxCommandEvent& event);
  //// end generated class members

  public:
    wxString GetTemplateName() const { return m_templatename; }
    wxString GetSymbolRef() const { return m_partref; }
    wxString GetSymbolName() const { return m_partname; }

    /** SetLibraryName() to test whether a symbol exists in the library, set the
     *  full path to the library before calling ShowModal() */
    void SetLibraryName(const wxString& filename) { m_libraryname = filename; }

  private:
    wxString m_templatename;  /* just the "base" name, without path or extension */
    wxString m_partname;    /* name for the symbol (output of the dialog) */
    wxString m_partref;   /* reference prefix for the symbol (output of the dialog) */
    wxString m_libraryname; /* name of the library where the new symbol must be stored in */
};

#endif // __libmngr_dlgnewsymbol__
