/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 5907$
 * $Date: 2018-12-14$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		5907
#define SVN_REVSTR	"1.4.5907"
#define SVN_REVDATE	"2018-12-14"
#define SVN_REVSTAMP	20181214L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
