/* This file was generated by the "svnrev" utility
 * (http://www.compuphase.com/svnrev.htm).
 * You should not modify it manually, as it may be re-generated.
 * 
 * $Revision: 5582$
 * $Date: 2016-10-03$
 */

#ifndef SVN_REV_H
#define SVN_REV_H

#define SVN_REV		5582
#define SVN_REVSTR	"1.2.5582"
#define SVN_REVDATE	"2016-10-03"
#define SVN_REVSTAMP	20161003L
#define SVN_REVMODIFIED	0

#endif /* SVN_REV_H */
